// FontAwesome.swift
//
// Copyright (c) 2014 Doan Truong Thi
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import UIKit

extension UIFont {
    class func fontAwesome(#size: CGFloat) -> UIFont {
        return UIFont(name: "FontAwesome", size: size)!
    }
}

enum FontAwesome : Int, Printable {
    var description : String {
        get {
            return FontAwesome.iconMap[self]!
        }
    }
    
    case adjust
    case adn
    case alignCenter
    case alignJustify
    case alignLeft
    case alignRight
    case ambulance
    case anchor
    case android
    case angellist
    case angleDoubleDown
    case angleDoubleLeft
    case angleDoubleRight
    case angleDoubleUp
    case angleDown
    case angleLeft
    case angleRight
    case angleUp
    case apple
    case archive
    case areaChart
    case arrowCircleDown
    case arrowCircleLeft
    case arrowCircleODown
    case arrowCircleOLeft
    case arrowCircleORight
    case arrowCircleOUp
    case arrowCircleRight
    case arrowCircleUp
    case arrowDown
    case arrowLeft
    case arrowRight
    case arrowUp
    case arrows
    case arrowsAlt
    case arrowsH
    case arrowsV
    case asterisk
    case at
    case automobile
    case backward
    case ban
    case bank
    case barChart
    case barChartO
    case barcode
    case bars
    case beer
    case behance
    case behanceSquare
    case bell
    case bellO
    case bellSlash
    case bellSlashO
    case bicycle
    case binoculars
    case birthdayCake
    case bitbucket
    case bitbucketSquare
    case bitcoin
    case bold
    case bolt
    case bomb
    case book
    case bookmark
    case bookmarkO
    case briefcase
    case btc
    case bug
    case building
    case buildingO
    case bullhorn
    case bullseye
    case bus
    case cab
    case calculator
    case calendar
    case calendarO
    case camera
    case cameraRetro
    case car
    case caretDown
    case caretLeft
    case caretRight
    case caretSquareODown
    case caretSquareOLeft
    case caretSquareORight
    case caretSquareOUp
    case caretUp
    case cc
    case ccAmex
    case ccDiscover
    case ccMastercard
    case ccPaypal
    case ccStripe
    case ccVisa
    case certificate
    case chain
    case chainBroken
    case check
    case checkCircle
    case checkCircleO
    case checkSquare
    case checkSquareO
    case chevronCircleDown
    case chevronCircleLeft
    case chevronCircleRight
    case chevronCircleUp
    case chevronDown
    case chevronLeft
    case chevronRight
    case chevronUp
    case child
    case circle
    case circleO
    case circleONotch
    case circleThin
    case clipboard
    case clockO
    case close
    case cloud
    case cloudDownload
    case cloudUpload
    case cny
    case code
    case codeFork
    case codepen
    case coffee
    case cog
    case cogs
    case columns
    case comment
    case commentO
    case comments
    case commentsO
    case compass
    case compress
    case copy
    case copyright
    case creditCard
    case crop
    case crosshairs
    case css3
    case cube
    case cubes
    case cut
    case cutlery
    case dashboard
    case database
    case dedent
    case delicious
    case desktop
    case deviantart
    case digg
    case dollar
    case dotCircleO
    case download
    case dribbble
    case dropbox
    case drupal
    case edit
    case eject
    case ellipsisH
    case ellipsisV
    case empire
    case envelope
    case envelopeO
    case envelopeSquare
    case eraser
    case eur
    case euro
    case exchange
    case exclamation
    case exclamationCircle
    case exclamationTriangle
    case expand
    case externalLink
    case externalLinkSquare
    case eye
    case eyeSlash
    case eyedropper
    case facebook
    case facebookSquare
    case fastBackward
    case fastForward
    case fax
    case female
    case fighterJet
    case file
    case fileArchiveO
    case fileAudioO
    case fileCodeO
    case fileExcelO
    case fileImageO
    case fileMovieO
    case fileO
    case filePdfO
    case filePhotoO
    case filePictureO
    case filePowerpointO
    case fileSoundO
    case fileText
    case fileTextO
    case fileVideoO
    case fileWordO
    case fileZipO
    case filesO
    case film
    case filter
    case fire
    case fireExtinguisher
    case flag
    case flagCheckered
    case flagO
    case flash
    case flask
    case flickr
    case floppyO
    case folder
    case folderO
    case folderOpen
    case folderOpenO
    case font
    case forward
    case foursquare
    case frownO
    case futbolO
    case gamepad
    case gavel
    case gbp
    case ge
    case gear
    case gears
    case gift
    case git
    case gitSquare
    case github
    case githubAlt
    case githubSquare
    case gittip
    case glass
    case globe
    case google
    case googlePlus
    case googlePlusSquare
    case googleWallet
    case graduationCap
    case group
    case hSquare
    case hackerNews
    case handODown
    case handOLeft
    case handORight
    case handOUp
    case hddO
    case header
    case headphones
    case heart
    case heartO
    case history
    case home
    case hospitalO
    case html5
    case ils
    case image
    case inbox
    case indent
    case info
    case infoCircle
    case inr
    case instagram
    case institution
    case ioxhost
    case italic
    case joomla
    case jpy
    case jsfiddle
    case key
    case keyboardO
    case krw
    case language
    case laptop
    case lastfm
    case lastfmSquare
    case leaf
    case legal
    case lemonO
    case levelDown
    case levelUp
    case lifeBouy
    case lifeBuoy
    case lifeRing
    case lifeSaver
    case lightbulbO
    case lineChart
    case link
    case linkedin
    case linkedinSquare
    case linux
    case list
    case listAlt
    case listOl
    case listUl
    case locationArrow
    case lock
    case longArrowDown
    case longArrowLeft
    case longArrowRight
    case longArrowUp
    case magic
    case magnet
    case mailForward
    case mailReply
    case mailReplyAll
    case male
    case mapMarker
    case maxcdn
    case meanpath
    case medkit
    case mehO
    case microphone
    case microphoneSlash
    case minus
    case minusCircle
    case minusSquare
    case minusSquareO
    case mobile
    case mobilePhone
    case money
    case moonO
    case mortarBoard
    case music
    case navicon
    case newspaperO
    case openid
    case outdent
    case pagelines
    case paintBrush
    case paperPlane
    case paperPlaneO
    case paperclip
    case paragraph
    case paste
    case pause
    case paw
    case paypal
    case pencil
    case pencilSquare
    case pencilSquareO
    case phone
    case phoneSquare
    case photo
    case pictureO
    case pieChart
    case piedPiper
    case piedPiperAlt
    case pinterest
    case pinterestSquare
    case plane
    case play
    case playCircle
    case playCircleO
    case plug
    case plus
    case plusCircle
    case plusSquare
    case plusSquareO
    case powerOff
    case print
    case puzzlePiece
    case qq
    case qrcode
    case question
    case questionCircle
    case quoteLeft
    case quoteRight
    case ra
    case random
    case rebel
    case recycle
    case reddit
    case redditSquare
    case refresh
    case remove
    case renren
    case reorder
    case repeat
    case reply
    case replyAll
    case retweet
    case rmb
    case road
    case rocket
    case rotateLeft
    case rotateRight
    case rouble
    case rss
    case rssSquare
    case rub
    case ruble
    case rupee
    case save
    case scissors
    case search
    case searchMinus
    case searchPlus
    case send
    case sendO
    case share
    case shareAlt
    case shareAltSquare
    case shareSquare
    case shareSquareO
    case shekel
    case sheqel
    case shield
    case shoppingCart
    case signIn
    case signOut
    case signal
    case sitemap
    case skype
    case slack
    case sliders
    case slideshare
    case smileO
    case soccerBallO
    case sort
    case sortAlphaAsc
    case sortAlphaDesc
    case sortAmountAsc
    case sortAmountDesc
    case sortAsc
    case sortDesc
    case sortDown
    case sortNumericAsc
    case sortNumericDesc
    case sortUp
    case soundcloud
    case spaceShuttle
    case spinner
    case spoon
    case spotify
    case square
    case squareO
    case stackExchange
    case stackOverflow
    case star
    case starHalf
    case starHalfEmpty
    case starHalfFull
    case starHalfO
    case starO
    case steam
    case steamSquare
    case stepBackward
    case stepForward
    case stethoscope
    case stop
    case strikethrough
    case stumbleupon
    case stumbleuponCircle
    case subScript
    case suitcase
    case sunO
    case superscript
    case support
    case table
    case tablet
    case tachometer
    case tag
    case tags
    case tasks
    case taxi
    case tencentWeibo
    case terminal
    case textHeight
    case textWidth
    case th
    case thLarge
    case thList
    case thumbTack
    case thumbsDown
    case thumbsODown
    case thumbsOUp
    case thumbsUp
    case ticket
    case times
    case timesCircle
    case timesCircleO
    case tint
    case toggleDown
    case toggleLeft
    case toggleOff
    case toggleOn
    case toggleRight
    case toggleUp
    case trash
    case trashO
    case tree
    case trello
    case trophy
    case truck
    case try
    case tty
    case tumblr
    case tumblrSquare
    case turkishLira
    case twitch
    case twitter
    case twitterSquare
    case umbrella
    case underline
    case undo
    case university
    case unlink
    case unlock
    case unlockAlt
    case unsorted
    case upload
    case usd
    case user
    case userMd
    case users
    case videoCamera
    case vimeoSquare
    case vine
    case vk
    case volumeDown
    case volumeOff
    case volumeUp
    case warning
    case wechat
    case weibo
    case weixin
    case wheelchair
    case wifi
    case windows
    case won
    case wordpress
    case wrench
    case xing
    case xingSquare
    case yahoo
    case yelp
    case yen
    case youtube
    case youtubePlay
    
    private static var iconMap: [FontAwesome: String] =  [
        FontAwesome.adjust: "\u{f042}",
        FontAwesome.adn: "\u{f170}",
        FontAwesome.alignCenter: "\u{f037}",
        FontAwesome.alignJustify: "\u{f039}",
        FontAwesome.alignLeft: "\u{f036}",
        FontAwesome.alignRight: "\u{f038}",
        FontAwesome.ambulance: "\u{f0f9}",
        FontAwesome.anchor: "\u{f13d}",
        FontAwesome.android: "\u{f17b}",
        FontAwesome.angellist: "\u{f209}",
        FontAwesome.angleDoubleDown: "\u{f103}",
        FontAwesome.angleDoubleLeft: "\u{f100}",
        FontAwesome.angleDoubleRight: "\u{f101}",
        FontAwesome.angleDoubleUp: "\u{f102}",
        FontAwesome.angleDown: "\u{f107}",
        FontAwesome.angleLeft: "\u{f104}",
        FontAwesome.angleRight: "\u{f105}",
        FontAwesome.angleUp: "\u{f106}",
        FontAwesome.apple: "\u{f179}",
        FontAwesome.archive: "\u{f187}",
        FontAwesome.areaChart: "\u{f1fe}",
        FontAwesome.arrowCircleDown: "\u{f0ab}",
        FontAwesome.arrowCircleLeft: "\u{f0a8}",
        FontAwesome.arrowCircleODown: "\u{f01a}",
        FontAwesome.arrowCircleOLeft: "\u{f190}",
        FontAwesome.arrowCircleORight: "\u{f18e}",
        FontAwesome.arrowCircleOUp: "\u{f01b}",
        FontAwesome.arrowCircleRight: "\u{f0a9}",
        FontAwesome.arrowCircleUp: "\u{f0aa}",
        FontAwesome.arrowDown: "\u{f063}",
        FontAwesome.arrowLeft: "\u{f060}",
        FontAwesome.arrowRight: "\u{f061}",
        FontAwesome.arrowUp: "\u{f062}",
        FontAwesome.arrows: "\u{f047}",
        FontAwesome.arrowsAlt: "\u{f0b2}",
        FontAwesome.arrowsH: "\u{f07e}",
        FontAwesome.arrowsV: "\u{f07d}",
        FontAwesome.asterisk: "\u{f069}",
        FontAwesome.at: "\u{f1fa}",
        FontAwesome.automobile: "\u{f1b9}",
        FontAwesome.backward: "\u{f04a}",
        FontAwesome.ban: "\u{f05e}",
        FontAwesome.bank: "\u{f19c}",
        FontAwesome.barChart: "\u{f080}",
        FontAwesome.barChartO: "\u{f080}",
        FontAwesome.barcode: "\u{f02a}",
        FontAwesome.bars: "\u{f0c9}",
        FontAwesome.beer: "\u{f0fc}",
        FontAwesome.behance: "\u{f1b4}",
        FontAwesome.behanceSquare: "\u{f1b5}",
        FontAwesome.bell: "\u{f0f3}",
        FontAwesome.bellO: "\u{f0a2}",
        FontAwesome.bellSlash: "\u{f1f6}",
        FontAwesome.bellSlashO: "\u{f1f7}",
        FontAwesome.bicycle: "\u{f206}",
        FontAwesome.binoculars: "\u{f1e5}",
        FontAwesome.birthdayCake: "\u{f1fd}",
        FontAwesome.bitbucket: "\u{f171}",
        FontAwesome.bitbucketSquare: "\u{f172}",
        FontAwesome.bitcoin: "\u{f15a}",
        FontAwesome.bold: "\u{f032}",
        FontAwesome.bolt: "\u{f0e7}",
        FontAwesome.bomb: "\u{f1e2}",
        FontAwesome.book: "\u{f02d}",
        FontAwesome.bookmark: "\u{f02e}",
        FontAwesome.bookmarkO: "\u{f097}",
        FontAwesome.briefcase: "\u{f0b1}",
        FontAwesome.btc: "\u{f15a}",
        FontAwesome.bug: "\u{f188}",
        FontAwesome.building: "\u{f1ad}",
        FontAwesome.buildingO: "\u{f0f7}",
        FontAwesome.bullhorn: "\u{f0a1}",
        FontAwesome.bullseye: "\u{f140}",
        FontAwesome.bus: "\u{f207}",
        FontAwesome.cab: "\u{f1ba}",
        FontAwesome.calculator: "\u{f1ec}",
        FontAwesome.calendar: "\u{f073}",
        FontAwesome.calendarO: "\u{f133}",
        FontAwesome.camera: "\u{f030}",
        FontAwesome.cameraRetro: "\u{f083}",
        FontAwesome.car: "\u{f1b9}",
        FontAwesome.caretDown: "\u{f0d7}",
        FontAwesome.caretLeft: "\u{f0d9}",
        FontAwesome.caretRight: "\u{f0da}",
        FontAwesome.caretSquareODown: "\u{f150}",
        FontAwesome.caretSquareOLeft: "\u{f191}",
        FontAwesome.caretSquareORight: "\u{f152}",
        FontAwesome.caretSquareOUp: "\u{f151}",
        FontAwesome.caretUp: "\u{f0d8}",
        FontAwesome.cc: "\u{f20a}",
        FontAwesome.ccAmex: "\u{f1f3}",
        FontAwesome.ccDiscover: "\u{f1f2}",
        FontAwesome.ccMastercard: "\u{f1f1}",
        FontAwesome.ccPaypal: "\u{f1f4}",
        FontAwesome.ccStripe: "\u{f1f5}",
        FontAwesome.ccVisa: "\u{f1f0}",
        FontAwesome.certificate: "\u{f0a3}",
        FontAwesome.chain: "\u{f0c1}",
        FontAwesome.chainBroken: "\u{f127}",
        FontAwesome.check: "\u{f00c}",
        FontAwesome.checkCircle: "\u{f058}",
        FontAwesome.checkCircleO: "\u{f05d}",
        FontAwesome.checkSquare: "\u{f14a}",
        FontAwesome.checkSquareO: "\u{f046}",
        FontAwesome.chevronCircleDown: "\u{f13a}",
        FontAwesome.chevronCircleLeft: "\u{f137}",
        FontAwesome.chevronCircleRight: "\u{f138}",
        FontAwesome.chevronCircleUp: "\u{f139}",
        FontAwesome.chevronDown: "\u{f078}",
        FontAwesome.chevronLeft: "\u{f053}",
        FontAwesome.chevronRight: "\u{f054}",
        FontAwesome.chevronUp: "\u{f077}",
        FontAwesome.child: "\u{f1ae}",
        FontAwesome.circle: "\u{f111}",
        FontAwesome.circleO: "\u{f10c}",
        FontAwesome.circleONotch: "\u{f1ce}",
        FontAwesome.circleThin: "\u{f1db}",
        FontAwesome.clipboard: "\u{f0ea}",
        FontAwesome.clockO: "\u{f017}",
        FontAwesome.close: "\u{f00d}",
        FontAwesome.cloud: "\u{f0c2}",
        FontAwesome.cloudDownload: "\u{f0ed}",
        FontAwesome.cloudUpload: "\u{f0ee}",
        FontAwesome.cny: "\u{f157}",
        FontAwesome.code: "\u{f121}",
        FontAwesome.codeFork: "\u{f126}",
        FontAwesome.codepen: "\u{f1cb}",
        FontAwesome.coffee: "\u{f0f4}",
        FontAwesome.cog: "\u{f013}",
        FontAwesome.cogs: "\u{f085}",
        FontAwesome.columns: "\u{f0db}",
        FontAwesome.comment: "\u{f075}",
        FontAwesome.commentO: "\u{f0e5}",
        FontAwesome.comments: "\u{f086}",
        FontAwesome.commentsO: "\u{f0e6}",
        FontAwesome.compass: "\u{f14e}",
        FontAwesome.compress: "\u{f066}",
        FontAwesome.copy: "\u{f0c5}",
        FontAwesome.copyright: "\u{f1f9}",
        FontAwesome.creditCard: "\u{f09d}",
        FontAwesome.crop: "\u{f125}",
        FontAwesome.crosshairs: "\u{f05b}",
        FontAwesome.css3: "\u{f13c}",
        FontAwesome.cube: "\u{f1b2}",
        FontAwesome.cubes: "\u{f1b3}",
        FontAwesome.cut: "\u{f0c4}",
        FontAwesome.cutlery: "\u{f0f5}",
        FontAwesome.dashboard: "\u{f0e4}",
        FontAwesome.database: "\u{f1c0}",
        FontAwesome.dedent: "\u{f03b}",
        FontAwesome.delicious: "\u{f1a5}",
        FontAwesome.desktop: "\u{f108}",
        FontAwesome.deviantart: "\u{f1bd}",
        FontAwesome.digg: "\u{f1a6}",
        FontAwesome.dollar: "\u{f155}",
        FontAwesome.dotCircleO: "\u{f192}",
        FontAwesome.download: "\u{f019}",
        FontAwesome.dribbble: "\u{f17d}",
        FontAwesome.dropbox: "\u{f16b}",
        FontAwesome.drupal: "\u{f1a9}",
        FontAwesome.edit: "\u{f044}",
        FontAwesome.eject: "\u{f052}",
        FontAwesome.ellipsisH: "\u{f141}",
        FontAwesome.ellipsisV: "\u{f142}",
        FontAwesome.empire: "\u{f1d1}",
        FontAwesome.envelope: "\u{f0e0}",
        FontAwesome.envelopeO: "\u{f003}",
        FontAwesome.envelopeSquare: "\u{f199}",
        FontAwesome.eraser: "\u{f12d}",
        FontAwesome.eur: "\u{f153}",
        FontAwesome.euro: "\u{f153}",
        FontAwesome.exchange: "\u{f0ec}",
        FontAwesome.exclamation: "\u{f12a}",
        FontAwesome.exclamationCircle: "\u{f06a}",
        FontAwesome.exclamationTriangle: "\u{f071}",
        FontAwesome.expand: "\u{f065}",
        FontAwesome.externalLink: "\u{f08e}",
        FontAwesome.externalLinkSquare: "\u{f14c}",
        FontAwesome.eye: "\u{f06e}",
        FontAwesome.eyeSlash: "\u{f070}",
        FontAwesome.eyedropper: "\u{f1fb}",
        FontAwesome.facebook: "\u{f09a}",
        FontAwesome.facebookSquare: "\u{f082}",
        FontAwesome.fastBackward: "\u{f049}",
        FontAwesome.fastForward: "\u{f050}",
        FontAwesome.fax: "\u{f1ac}",
        FontAwesome.female: "\u{f182}",
        FontAwesome.fighterJet: "\u{f0fb}",
        FontAwesome.file: "\u{f15b}",
        FontAwesome.fileArchiveO: "\u{f1c6}",
        FontAwesome.fileAudioO: "\u{f1c7}",
        FontAwesome.fileCodeO: "\u{f1c9}",
        FontAwesome.fileExcelO: "\u{f1c3}",
        FontAwesome.fileImageO: "\u{f1c5}",
        FontAwesome.fileMovieO: "\u{f1c8}",
        FontAwesome.fileO: "\u{f016}",
        FontAwesome.filePdfO: "\u{f1c1}",
        FontAwesome.filePhotoO: "\u{f1c5}",
        FontAwesome.filePictureO: "\u{f1c5}",
        FontAwesome.filePowerpointO: "\u{f1c4}",
        FontAwesome.fileSoundO: "\u{f1c7}",
        FontAwesome.fileText: "\u{f15c}",
        FontAwesome.fileTextO: "\u{f0f6}",
        FontAwesome.fileVideoO: "\u{f1c8}",
        FontAwesome.fileWordO: "\u{f1c2}",
        FontAwesome.fileZipO: "\u{f1c6}",
        FontAwesome.filesO: "\u{f0c5}",
        FontAwesome.film: "\u{f008}",
        FontAwesome.filter: "\u{f0b0}",
        FontAwesome.fire: "\u{f06d}",
        FontAwesome.fireExtinguisher: "\u{f134}",
        FontAwesome.flag: "\u{f024}",
        FontAwesome.flagCheckered: "\u{f11e}",
        FontAwesome.flagO: "\u{f11d}",
        FontAwesome.flash: "\u{f0e7}",
        FontAwesome.flask: "\u{f0c3}",
        FontAwesome.flickr: "\u{f16e}",
        FontAwesome.floppyO: "\u{f0c7}",
        FontAwesome.folder: "\u{f07b}",
        FontAwesome.folderO: "\u{f114}",
        FontAwesome.folderOpen: "\u{f07c}",
        FontAwesome.folderOpenO: "\u{f115}",
        FontAwesome.font: "\u{f031}",
        FontAwesome.forward: "\u{f04e}",
        FontAwesome.foursquare: "\u{f180}",
        FontAwesome.frownO: "\u{f119}",
        FontAwesome.futbolO: "\u{f1e3}",
        FontAwesome.gamepad: "\u{f11b}",
        FontAwesome.gavel: "\u{f0e3}",
        FontAwesome.gbp: "\u{f154}",
        FontAwesome.ge: "\u{f1d1}",
        FontAwesome.gear: "\u{f013}",
        FontAwesome.gears: "\u{f085}",
        FontAwesome.gift: "\u{f06b}",
        FontAwesome.git: "\u{f1d3}",
        FontAwesome.gitSquare: "\u{f1d2}",
        FontAwesome.github: "\u{f09b}",
        FontAwesome.githubAlt: "\u{f113}",
        FontAwesome.githubSquare: "\u{f092}",
        FontAwesome.gittip: "\u{f184}",
        FontAwesome.glass: "\u{f000}",
        FontAwesome.globe: "\u{f0ac}",
        FontAwesome.google: "\u{f1a0}",
        FontAwesome.googlePlus: "\u{f0d5}",
        FontAwesome.googlePlusSquare: "\u{f0d4}",
        FontAwesome.googleWallet: "\u{f1ee}",
        FontAwesome.graduationCap: "\u{f19d}",
        FontAwesome.group: "\u{f0c0}",
        FontAwesome.hSquare: "\u{f0fd}",
        FontAwesome.hackerNews: "\u{f1d4}",
        FontAwesome.handODown: "\u{f0a7}",
        FontAwesome.handOLeft: "\u{f0a5}",
        FontAwesome.handORight: "\u{f0a4}",
        FontAwesome.handOUp: "\u{f0a6}",
        FontAwesome.hddO: "\u{f0a0}",
        FontAwesome.header: "\u{f1dc}",
        FontAwesome.headphones: "\u{f025}",
        FontAwesome.heart: "\u{f004}",
        FontAwesome.heartO: "\u{f08a}",
        FontAwesome.history: "\u{f1da}",
        FontAwesome.home: "\u{f015}",
        FontAwesome.hospitalO: "\u{f0f8}",
        FontAwesome.html5: "\u{f13b}",
        FontAwesome.ils: "\u{f20b}",
        FontAwesome.image: "\u{f03e}",
        FontAwesome.inbox: "\u{f01c}",
        FontAwesome.indent: "\u{f03c}",
        FontAwesome.info: "\u{f129}",
        FontAwesome.infoCircle: "\u{f05a}",
        FontAwesome.inr: "\u{f156}",
        FontAwesome.instagram: "\u{f16d}",
        FontAwesome.institution: "\u{f19c}",
        FontAwesome.ioxhost: "\u{f208}",
        FontAwesome.italic: "\u{f033}",
        FontAwesome.joomla: "\u{f1aa}",
        FontAwesome.jpy: "\u{f157}",
        FontAwesome.jsfiddle: "\u{f1cc}",
        FontAwesome.key: "\u{f084}",
        FontAwesome.keyboardO: "\u{f11c}",
        FontAwesome.krw: "\u{f159}",
        FontAwesome.language: "\u{f1ab}",
        FontAwesome.laptop: "\u{f109}",
        FontAwesome.lastfm: "\u{f202}",
        FontAwesome.lastfmSquare: "\u{f203}",
        FontAwesome.leaf: "\u{f06c}",
        FontAwesome.legal: "\u{f0e3}",
        FontAwesome.lemonO: "\u{f094}",
        FontAwesome.levelDown: "\u{f149}",
        FontAwesome.levelUp: "\u{f148}",
        FontAwesome.lifeBouy: "\u{f1cd}",
        FontAwesome.lifeBuoy: "\u{f1cd}",
        FontAwesome.lifeRing: "\u{f1cd}",
        FontAwesome.lifeSaver: "\u{f1cd}",
        FontAwesome.lightbulbO: "\u{f0eb}",
        FontAwesome.lineChart: "\u{f201}",
        FontAwesome.link: "\u{f0c1}",
        FontAwesome.linkedin: "\u{f0e1}",
        FontAwesome.linkedinSquare: "\u{f08c}",
        FontAwesome.linux: "\u{f17c}",
        FontAwesome.list: "\u{f03a}",
        FontAwesome.listAlt: "\u{f022}",
        FontAwesome.listOl: "\u{f0cb}",
        FontAwesome.listUl: "\u{f0ca}",
        FontAwesome.locationArrow: "\u{f124}",
        FontAwesome.lock: "\u{f023}",
        FontAwesome.longArrowDown: "\u{f175}",
        FontAwesome.longArrowLeft: "\u{f177}",
        FontAwesome.longArrowRight: "\u{f178}",
        FontAwesome.longArrowUp: "\u{f176}",
        FontAwesome.magic: "\u{f0d0}",
        FontAwesome.magnet: "\u{f076}",
        FontAwesome.mailForward: "\u{f064}",
        FontAwesome.mailReply: "\u{f112}",
        FontAwesome.mailReplyAll: "\u{f122}",
        FontAwesome.male: "\u{f183}",
        FontAwesome.mapMarker: "\u{f041}",
        FontAwesome.maxcdn: "\u{f136}",
        FontAwesome.meanpath: "\u{f20c}",
        FontAwesome.medkit: "\u{f0fa}",
        FontAwesome.mehO: "\u{f11a}",
        FontAwesome.microphone: "\u{f130}",
        FontAwesome.microphoneSlash: "\u{f131}",
        FontAwesome.minus: "\u{f068}",
        FontAwesome.minusCircle: "\u{f056}",
        FontAwesome.minusSquare: "\u{f146}",
        FontAwesome.minusSquareO: "\u{f147}",
        FontAwesome.mobile: "\u{f10b}",
        FontAwesome.mobilePhone: "\u{f10b}",
        FontAwesome.money: "\u{f0d6}",
        FontAwesome.moonO: "\u{f186}",
        FontAwesome.mortarBoard: "\u{f19d}",
        FontAwesome.music: "\u{f001}",
        FontAwesome.navicon: "\u{f0c9}",
        FontAwesome.newspaperO: "\u{f1ea}",
        FontAwesome.openid: "\u{f19b}",
        FontAwesome.outdent: "\u{f03b}",
        FontAwesome.pagelines: "\u{f18c}",
        FontAwesome.paintBrush: "\u{f1fc}",
        FontAwesome.paperPlane: "\u{f1d8}",
        FontAwesome.paperPlaneO: "\u{f1d9}",
        FontAwesome.paperclip: "\u{f0c6}",
        FontAwesome.paragraph: "\u{f1dd}",
        FontAwesome.paste: "\u{f0ea}",
        FontAwesome.pause: "\u{f04c}",
        FontAwesome.paw: "\u{f1b0}",
        FontAwesome.paypal: "\u{f1ed}",
        FontAwesome.pencil: "\u{f040}",
        FontAwesome.pencilSquare: "\u{f14b}",
        FontAwesome.pencilSquareO: "\u{f044}",
        FontAwesome.phone: "\u{f095}",
        FontAwesome.phoneSquare: "\u{f098}",
        FontAwesome.photo: "\u{f03e}",
        FontAwesome.pictureO: "\u{f03e}",
        FontAwesome.pieChart: "\u{f200}",
        FontAwesome.piedPiper: "\u{f1a7}",
        FontAwesome.piedPiperAlt: "\u{f1a8}",
        FontAwesome.pinterest: "\u{f0d2}",
        FontAwesome.pinterestSquare: "\u{f0d3}",
        FontAwesome.plane: "\u{f072}",
        FontAwesome.play: "\u{f04b}",
        FontAwesome.playCircle: "\u{f144}",
        FontAwesome.playCircleO: "\u{f01d}",
        FontAwesome.plug: "\u{f1e6}",
        FontAwesome.plus: "\u{f067}",
        FontAwesome.plusCircle: "\u{f055}",
        FontAwesome.plusSquare: "\u{f0fe}",
        FontAwesome.plusSquareO: "\u{f196}",
        FontAwesome.powerOff: "\u{f011}",
        FontAwesome.print: "\u{f02f}",
        FontAwesome.puzzlePiece: "\u{f12e}",
        FontAwesome.qq: "\u{f1d6}",
        FontAwesome.qrcode: "\u{f029}",
        FontAwesome.question: "\u{f128}",
        FontAwesome.questionCircle: "\u{f059}",
        FontAwesome.quoteLeft: "\u{f10d}",
        FontAwesome.quoteRight: "\u{f10e}",
        FontAwesome.ra: "\u{f1d0}",
        FontAwesome.random: "\u{f074}",
        FontAwesome.rebel: "\u{f1d0}",
        FontAwesome.recycle: "\u{f1b8}",
        FontAwesome.reddit: "\u{f1a1}",
        FontAwesome.redditSquare: "\u{f1a2}",
        FontAwesome.refresh: "\u{f021}",
        FontAwesome.remove: "\u{f00d}",
        FontAwesome.renren: "\u{f18b}",
        FontAwesome.reorder: "\u{f0c9}",
        FontAwesome.repeat: "\u{f01e}",
        FontAwesome.reply: "\u{f112}",
        FontAwesome.replyAll: "\u{f122}",
        FontAwesome.retweet: "\u{f079}",
        FontAwesome.rmb: "\u{f157}",
        FontAwesome.road: "\u{f018}",
        FontAwesome.rocket: "\u{f135}",
        FontAwesome.rotateLeft: "\u{f0e2}",
        FontAwesome.rotateRight: "\u{f01e}",
        FontAwesome.rouble: "\u{f158}",
        FontAwesome.rss: "\u{f09e}",
        FontAwesome.rssSquare: "\u{f143}",
        FontAwesome.rub: "\u{f158}",
        FontAwesome.ruble: "\u{f158}",
        FontAwesome.rupee: "\u{f156}",
        FontAwesome.save: "\u{f0c7}",
        FontAwesome.scissors: "\u{f0c4}",
        FontAwesome.search: "\u{f002}",
        FontAwesome.searchMinus: "\u{f010}",
        FontAwesome.searchPlus: "\u{f00e}",
        FontAwesome.send: "\u{f1d8}",
        FontAwesome.sendO: "\u{f1d9}",
        FontAwesome.share: "\u{f064}",
        FontAwesome.shareAlt: "\u{f1e0}",
        FontAwesome.shareAltSquare: "\u{f1e1}",
        FontAwesome.shareSquare: "\u{f14d}",
        FontAwesome.shareSquareO: "\u{f045}",
        FontAwesome.shekel: "\u{f20b}",
        FontAwesome.sheqel: "\u{f20b}",
        FontAwesome.shield: "\u{f132}",
        FontAwesome.shoppingCart: "\u{f07a}",
        FontAwesome.signIn: "\u{f090}",
        FontAwesome.signOut: "\u{f08b}",
        FontAwesome.signal: "\u{f012}",
        FontAwesome.sitemap: "\u{f0e8}",
        FontAwesome.skype: "\u{f17e}",
        FontAwesome.slack: "\u{f198}",
        FontAwesome.sliders: "\u{f1de}",
        FontAwesome.slideshare: "\u{f1e7}",
        FontAwesome.smileO: "\u{f118}",
        FontAwesome.soccerBallO: "\u{f1e3}",
        FontAwesome.sort: "\u{f0dc}",
        FontAwesome.sortAlphaAsc: "\u{f15d}",
        FontAwesome.sortAlphaDesc: "\u{f15e}",
        FontAwesome.sortAmountAsc: "\u{f160}",
        FontAwesome.sortAmountDesc: "\u{f161}",
        FontAwesome.sortAsc: "\u{f0de}",
        FontAwesome.sortDesc: "\u{f0dd}",
        FontAwesome.sortDown: "\u{f0dd}",
        FontAwesome.sortNumericAsc: "\u{f162}",
        FontAwesome.sortNumericDesc: "\u{f163}",
        FontAwesome.sortUp: "\u{f0de}",
        FontAwesome.soundcloud: "\u{f1be}",
        FontAwesome.spaceShuttle: "\u{f197}",
        FontAwesome.spinner: "\u{f110}",
        FontAwesome.spoon: "\u{f1b1}",
        FontAwesome.spotify: "\u{f1bc}",
        FontAwesome.square: "\u{f0c8}",
        FontAwesome.squareO: "\u{f096}",
        FontAwesome.stackExchange: "\u{f18d}",
        FontAwesome.stackOverflow: "\u{f16c}",
        FontAwesome.star: "\u{f005}",
        FontAwesome.starHalf: "\u{f089}",
        FontAwesome.starHalfEmpty: "\u{f123}",
        FontAwesome.starHalfFull: "\u{f123}",
        FontAwesome.starHalfO: "\u{f123}",
        FontAwesome.starO: "\u{f006}",
        FontAwesome.steam: "\u{f1b6}",
        FontAwesome.steamSquare: "\u{f1b7}",
        FontAwesome.stepBackward: "\u{f048}",
        FontAwesome.stepForward: "\u{f051}",
        FontAwesome.stethoscope: "\u{f0f1}",
        FontAwesome.stop: "\u{f04d}",
        FontAwesome.strikethrough: "\u{f0cc}",
        FontAwesome.stumbleupon: "\u{f1a4}",
        FontAwesome.stumbleuponCircle: "\u{f1a3}",
        FontAwesome.subScript: "\u{f12c}",
        FontAwesome.suitcase: "\u{f0f2}",
        FontAwesome.sunO: "\u{f185}",
        FontAwesome.superscript: "\u{f12b}",
        FontAwesome.support: "\u{f1cd}",
        FontAwesome.table: "\u{f0ce}",
        FontAwesome.tablet: "\u{f10a}",
        FontAwesome.tachometer: "\u{f0e4}",
        FontAwesome.tag: "\u{f02b}",
        FontAwesome.tags: "\u{f02c}",
        FontAwesome.tasks: "\u{f0ae}",
        FontAwesome.taxi: "\u{f1ba}",
        FontAwesome.tencentWeibo: "\u{f1d5}",
        FontAwesome.terminal: "\u{f120}",
        FontAwesome.textHeight: "\u{f034}",
        FontAwesome.textWidth: "\u{f035}",
        FontAwesome.th: "\u{f00a}",
        FontAwesome.thLarge: "\u{f009}",
        FontAwesome.thList: "\u{f00b}",
        FontAwesome.thumbTack: "\u{f08d}",
        FontAwesome.thumbsDown: "\u{f165}",
        FontAwesome.thumbsODown: "\u{f088}",
        FontAwesome.thumbsOUp: "\u{f087}",
        FontAwesome.thumbsUp: "\u{f164}",
        FontAwesome.ticket: "\u{f145}",
        FontAwesome.times: "\u{f00d}",
        FontAwesome.timesCircle: "\u{f057}",
        FontAwesome.timesCircleO: "\u{f05c}",
        FontAwesome.tint: "\u{f043}",
        FontAwesome.toggleDown: "\u{f150}",
        FontAwesome.toggleLeft: "\u{f191}",
        FontAwesome.toggleOff: "\u{f204}",
        FontAwesome.toggleOn: "\u{f205}",
        FontAwesome.toggleRight: "\u{f152}",
        FontAwesome.toggleUp: "\u{f151}",
        FontAwesome.trash: "\u{f1f8}",
        FontAwesome.trashO: "\u{f014}",
        FontAwesome.tree: "\u{f1bb}",
        FontAwesome.trello: "\u{f181}",
        FontAwesome.trophy: "\u{f091}",
        FontAwesome.truck: "\u{f0d1}",
        FontAwesome.try: "\u{f195}",
        FontAwesome.tty: "\u{f1e4}",
        FontAwesome.tumblr: "\u{f173}",
        FontAwesome.tumblrSquare: "\u{f174}",
        FontAwesome.turkishLira: "\u{f195}",
        FontAwesome.twitch: "\u{f1e8}",
        FontAwesome.twitter: "\u{f099}",
        FontAwesome.twitterSquare: "\u{f081}",
        FontAwesome.umbrella: "\u{f0e9}",
        FontAwesome.underline: "\u{f0cd}",
        FontAwesome.undo: "\u{f0e2}",
        FontAwesome.university: "\u{f19c}",
        FontAwesome.unlink: "\u{f127}",
        FontAwesome.unlock: "\u{f09c}",
        FontAwesome.unlockAlt: "\u{f13e}",
        FontAwesome.unsorted: "\u{f0dc}",
        FontAwesome.upload: "\u{f093}",
        FontAwesome.usd: "\u{f155}",
        FontAwesome.user: "\u{f007}",
        FontAwesome.userMd: "\u{f0f0}",
        FontAwesome.users: "\u{f0c0}",
        FontAwesome.videoCamera: "\u{f03d}",
        FontAwesome.vimeoSquare: "\u{f194}",
        FontAwesome.vine: "\u{f1ca}",
        FontAwesome.vk: "\u{f189}",
        FontAwesome.volumeDown: "\u{f027}",
        FontAwesome.volumeOff: "\u{f026}",
        FontAwesome.volumeUp: "\u{f028}",
        FontAwesome.warning: "\u{f071}",
        FontAwesome.wechat: "\u{f1d7}",
        FontAwesome.weibo: "\u{f18a}",
        FontAwesome.weixin: "\u{f1d7}",
        FontAwesome.wheelchair: "\u{f193}",
        FontAwesome.wifi: "\u{f1eb}",
        FontAwesome.windows: "\u{f17a}",
        FontAwesome.won: "\u{f159}",
        FontAwesome.wordpress: "\u{f19a}",
        FontAwesome.wrench: "\u{f0ad}",
        FontAwesome.xing: "\u{f168}",
        FontAwesome.xingSquare: "\u{f169}",
        FontAwesome.yahoo: "\u{f19e}",
        FontAwesome.yelp: "\u{f1e9}",
        FontAwesome.yen: "\u{f157}",
        FontAwesome.youtube: "\u{f167}",
        FontAwesome.youtubePlay: "\u{f16a}"
    ]
}
